import { Colors as ThemeColors } from './Theme';

export default {
  light: {
    text: ThemeColors.pearl,
    background: ThemeColors.obsidian,
    tint: ThemeColors.aqua,
    tabIconDefault: ThemeColors.titanium,
    tabIconSelected: ThemeColors.aqua,
    aqua: ThemeColors.aqua,
    violet: ThemeColors.violet,
    coral: ThemeColors.coral,
    blue: ThemeColors.blue,
    pearl: ThemeColors.pearl,
    titanium: ThemeColors.titanium,
    slate: ThemeColors.slate,
    obsidian: ThemeColors.obsidian,
    abyss: ThemeColors.abyss,
    midnight: ThemeColors.midnight,
    success: ThemeColors.success,
    warning: ThemeColors.warning,
    danger: ThemeColors.danger,
  },
  dark: {
    text: ThemeColors.pearl,
    background: ThemeColors.obsidian,
    tint: ThemeColors.aqua,
    tabIconDefault: ThemeColors.titanium,
    tabIconSelected: ThemeColors.aqua,
    aqua: ThemeColors.aqua,
    violet: ThemeColors.violet,
    coral: ThemeColors.coral,
    blue: ThemeColors.blue,
    pearl: ThemeColors.pearl,
    titanium: ThemeColors.titanium,
    slate: ThemeColors.slate,
    obsidian: ThemeColors.obsidian,
    abyss: ThemeColors.abyss,
    midnight: ThemeColors.midnight,
    success: ThemeColors.success,
    warning: ThemeColors.warning,
    danger: ThemeColors.danger,
  },
};
